#-------------------------------
# General Site Settings
title: Muskan Jain

#-------------------------------
# Author Settings
author:
  name: Muskan Jain
  image: Professional_photo1.png
  say-hello: Hello there! I’m <strong>Muskan Jain</strong>
  bio: I am a digital innovation enthusiast with a strong technology background. With a burning curiosity to explore new horizons, I actively seek exciting job opportunities to apply my skills and push the boundaries of what's possible.<br> <strong>Education:</strong> MS in Computer Science and  Engineering,<br>       -The Ohio State University <br><strong>Interests:</strong> Data Science, Software Development<br> <strong>Email:</strong> jain.727@osu.edu | muskaanajain@gmail.com
#-------------------------------
# Contact links
email: jain.727@osu.edu
linkedin: https://www.linkedin.com/in/muskanjaincs/
github: https://github.com/MuskanJain798
