#-------------------------------
# General Site Settings
title: Muskan Jain

#-------------------------------
# Author Settings
author:
  name: Muskan Jain
  image: Professional_photo.jpeg
  say-hello: Hello there! I’m <strong>Muskan Jain</strong>
  bio : Pursuing Master of Science in Computer Science and Engineering at The Ohio State University <be>I am  a digital innovation enthusiast with a strong background in technology.  With a burning curiosity to explore new horizons, I'm actively seeking exciting job opportunities where I can apply my skills and push the boundaries of what's possible.<br> **Interests:** Data Science, Software Development<br>**Email:** jain.727@osu.edu | muskaanajain@gmail.com
#-------------------------------
# Contact links
email: jain.727@osu.edu
linkedin: https://www.linkedin.com/in/muskanjaincs/
github: https://github.com/MuskanJain798
